version: "3"
services:
    php:
        build:
            context: ./data/php
        restart: unless-stopped
        volumes:
            - ./data/config/pool.conf:/usr/local/etc/php-fpm.d/pool.conf
            - nicepic_data:/var/www:Z
            - nicepic_files:/var/nicepic:Z
    nginx:
        build:
            context: ./data/nginx
        depends_on:
            - php
        restart: always
        volumes:
            - ./data/config/nginx.conf:/etc/nginx/nginx.conf
            - ./data/config/default.conf.template:/etc/nginx/templates/default.conf.template
            - nicepic_data:/var/www:Z
            - nicepic_files:/var/nicepic:Z
        ports:
            - "${HTTP_PORT:-80}:80"
        environment:
            - DB_SERVER=${DB_SERVER}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - MAX_THUMB=${MAX_THUMB}
            - MAX_SMALL=${MAX_SMALL}
            - CACHE_TIME=${CACHE_TIME}

    nicepic_client:
        image: dev4pro/nicepic:data
        command: tail -f /dev/null
        volumes:
            - nicepic_data:/var/www:Z
            - nicepic_files:/var/nicepic:Z
volumes:
    nicepic_data:
    nicepic_files:
